modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/mcrib884/rei-recipe-history/issues"
license = "MIT"

[[mods]]
modId = "reirecipehistory"
version = "${version}"
displayName = "REI Recipe History"
authors = "mcrib884"
description = '''
Adds browsing history to Roughly Enough Items. Tracks viewed recipes and displays them in a panel at the bottom of the item list.
'''

[[dependencies.reirecipehistory]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reirecipehistory]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.reirecipehistory]]
modId = "roughlyenoughitems"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "CLIENT"